# Generated by Django 4.1.7 on 2023-05-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_lines',
            new_name='no_of_likes',
        ),
    ]
